# Generated by Django 4.1.3 on 2022-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_typespeculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='personnes_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='salaire_minimum',
            field=models.IntegerField(default=0),
        ),
    ]
