# Generated by Django 4.1.3 on 2022-11-07 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_typespeculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('speculation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='users.typespeculation')),
                ('typeactivite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='users.typeactivte')),
            ],
        ),
    ]
