# Generated by Django 4.1.3 on 2022-11-07 01:47

import activite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_typespeculation'),
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='activite',
            name='speculation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speculations', to='users.typespeculation'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='typeactivite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='users.typeactivte'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefices', models.IntegerField()),
                ('depenses', models.IntegerField()),
                ('vente', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='activite.etape')),
            ],
        ),
        migrations.CreateModel(
            name='ImageEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=activite.models.upload_to)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activite.etape')),
            ],
        ),
        migrations.AddField(
            model_name='etape',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='activite.activite'),
        ),
    ]
