# Generated by Django 4.1.3 on 2022-11-07 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_etape_alter_activite_speculation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageetape',
            old_name='sujet',
            new_name='etape',
        ),
        migrations.AlterField(
            model_name='etape',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='activite.activite'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='activite.etape'),
        ),
    ]
