# Generated by Django 4.1.3 on 2022-11-07 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activite', '0003_rename_sujet_imageetape_etape_alter_etape_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL),
        ),
    ]
