# Generated by Django 4.1.3 on 2022-11-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0004_activite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rendement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendements', to='activite.etape')),
            ],
        ),
    ]
